create table if not exists tb_application_master (
    application_id bigint primary key,
    application_name varchar(255) not null,
    application_key varchar(255) not null
);

create table if not exists tb_node_history_master (
    application_id bigint not null,
    analysis_time varchar(255) not null,
    created_at timestamp not null default current_timestamp,
    primary key (application_id, analysis_time)
);

create table if not exists tb_node_history (
    application_id bigint not null,
    analysis_time varchar(255) not null,
    node_id bigint not null,
    node_name varchar(2000) not null,
    node_type varchar(30) not null,
    use_yn boolean not null default true,
    primary key (application_id, analysis_time, node_id)
);

create table if not exists tb_node_detail_history (
    application_id bigint not null,
    analysis_time varchar(255) not null,
    node_id bigint not null,
    split_node_level int not null,
    split_node_name varchar(2000) not null,
    split_node_type varchar(30) not null,
    primary key (application_id, analysis_time, node_id, split_node_level)
);

create table if not exists tb_node_relation_history (
    application_id bigint not null,
    analysis_time varchar(255) not null,
    relation_id bigint not null,
    source_node_id bigint not null,
    target_node_id bigint not null,
    relation_type varchar(50) not null,
    primary key (application_id, analysis_time, relation_id)
);

drop table if exists tb_gi_subsystems_history_master cascade;
drop table if exists tb_gi_subsystems_history cascade;
drop table if exists tb_gi_subsystems_llm_summary cascade;

create table if not exists tb_gi_subsystems_history (
    discovery_run_id bigint generated by default as identity primary key,
    analysis_time varchar(255) not null,
    run_sequence int not null default 1,
    runs int not null default 10,
    consensus_threshold decimal(8,4) not null default 0.70,
    resolution decimal(8,4) not null default 1.00,
    discovery_result clob not null,
    total_subsystems int,
    avg_stability_score decimal(8,4),
    started_at timestamp,
    completed_at timestamp,
    created_at timestamp not null default current_timestamp,
    created_by_envelope bytea,
    created_by_hash bytea
);

create table if not exists tb_gi_subsystems_llm_summary (
    summary_id bigint generated by default as identity primary key,
    discovery_run_id bigint not null,
    llm_model varchar(128) not null,
    summary_type varchar(64) not null,
    summary_text clob not null,
    created_at timestamp not null default current_timestamp,
    constraint uq_subsystems_llm_summary unique (discovery_run_id, llm_model, summary_type)
);

create index if not exists idx_node_history_snapshot
    on tb_node_history (application_id, analysis_time);

create index if not exists idx_node_detail_snapshot
    on tb_node_detail_history (application_id, analysis_time, node_id);

create index if not exists idx_relation_history_snapshot
    on tb_node_relation_history (application_id, analysis_time);

create index if not exists idx_subsystem_run_config
    on tb_gi_subsystems_history (
        analysis_time,
        runs,
        consensus_threshold,
        resolution
    );
